name = "onewishes"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

routes = [
  { pattern = "onewishes.com", custom_domain = true },
  { pattern = "www.onewishes.com", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Uncomment if you enable ISR caching:
# [[kv_namespaces]]
# binding = "NEXT_CACHE_KV"
# id = "your-kv-namespace-id"
